import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
export const metadata: Metadata = {
  title: "PLC Academy",
  description: "Generated by PLC Academy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="body">{children}</body>
    </html>
  );
}
